matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: shell
      python: "2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
sudo: false
git:
  submodules: false
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - GOOGLE_APPLICATION_CREDENTIALS=travis-gcp-service-account-credentials.json
  - DSS_TEST_STAGE=dev
  - BOTO_CONFIG=/dev/null
before_install:
  - openssl aes-256-cbc -K $encrypted_266b385b8e6e_key -iv $encrypted_266b385b8e6e_iv
    -in travis-gcp-service-account-credentials.json.enc -out travis-gcp-service-account-credentials.json
    -d
  - sed -i -e s/dss.data.humancellatlas.org/dss.$DSS_TEST_STAGE.data.humancellatlas.org/ hca/default_config.json
install:
  - pip install -r requirements-dev.txt
  - wget -O regex.json https://raw.githubusercontent.com/HumanCellAtlas/dcplib/master/components/trufflehog_regex_patterns.json
  - trufflehog --regex --rules regex.json --entropy=False https://github.com/HumanCellAtlas/data-store.git
  - rm regex.json
  - make install
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)


